rsvplist.node_settings:
  type: config_object
  label: 'RSVP node settings'
  mapping:
    nodes:
      type: mapping
      label: 'Per-node RSVP enabled flags'
      mapping:
        '*':
          type: boolean
